[package]
name = "lock"
version = "0.1.0"
authors = ["Halvor Bø <hfb@complex.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
